### ISSUE TITLE
Not running under Windows10

### ISSUE THREAD

**Issue by nate2014jatc** [Malexion/Rhythm-Bot#1]
Hi, I'm trying to get this up and running, 
I'm on Windows 10 with Python 2.7.14, Node.js LTS, and the Latest FFMPEG

I've made the token, and put it into the config, and I get the following error on launch;

```
Disconnected.
(node:5840) UnhandledPromiseRejectionRejectionWarning: Unhandled promise rejection (rejection id: 1): Error: Incorrect login details were provided.
(node:5840) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

What advice do you have?

**Comment by Malexion** [comment]
Sounds a bit like the login is being rejected, you don't have the "<" or ">" around the token right?

And the token came from https://discordapp.com/developers where you register an "app" under "my apps" on the left and find the token correct?
![image](https://user-images.githubusercontent.com/5237473/34017507-a4c43c7c-e0eb-11e7-8f5d-fd225c50f5b4.png)

**Comment by Malexion** [comment]
Also just pushed an update for logging of errors, so it should create a file in the base directory called "rhythm-bot-log.log" to sort of assist with future errors.

**Comment by nate2014jatc** [comment]
The ">" and "<" characters are not present in my app token.
The token came from the correct place, as you've shown.
[rhythm-bot-log.log](https://github.com/Malexion/Rhythm-Bot/files/1561061/rhythm-bot-log.log)

**Comment by nate2014jatc** [comment]
Can this be run safely under Linux, or is it bound to Windows?

**Comment by Malexion** [comment]
I think FFMPEG works better on Linux, but I'm not entirely sure I haven't test it on Linux.

And did you modify config.js?

**Comment by nate2014jatc** [comment]
Yeah, I attached it below with a fake token

On December 14, 2017 4:18:20 PM MST, Malexion <notifications@github.com> wrote:
>I think FFMPEG works better on Linux, but I'm not entirely sure I
>haven't test it on Linux.
>
>And did you modify config.js?
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/Malexion/Rhythm-Bot/issues/1#issuecomment-351865742

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by Malexion** [comment]
config.js holds the default config settings any modifications you want to make to the config should be passed through main.js in that object that's inserted into the class. 

It recursively updates the underlying config so you only have to define the properties you want to update.

**Comment by nate2014jatc** [comment]
Would you elaborate please?

On December 14, 2017 4:20:49 PM MST, Malexion <notifications@github.com> wrote:
>config.js holds the default config settings any modifications you want
>to make to the config should be passed through main.js in that object
>that's inserted into the class. 
>
>It recursively updates the underlying config so you only have to define
>the properties you want to update.
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/Malexion/Rhythm-Bot/issues/1#issuecomment-351866207

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by Malexion** [comment]
You'd pretty much want to leave config.js untouched unless your adding features of your own and make config adjustments in main.js like show with the commented out properties. 

![image](https://user-images.githubusercontent.com/5237473/34019257-9c2c70c2-e0f3-11e7-8ffe-1c931963effe.png)

**Comment by Malexion** [comment]
The config is smart enough to only update properties listed. so auto.deafen would be updated if un-commented but the other properties in the auto category would be left alone.

**Comment by nate2014jatc** [comment]
I see...
That's a bit unintuitive.

A section in the Readme would be beneficial I think. 
-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by nate2014jatc** [comment]
I'm going to try running this under Ubuntu 17.04 and see what happens.

This time, I'll put the token in the right spot XP

Out of curiosity, is this the source for ***THE*** Rhythm Bot?

**Comment by nate2014jatc** [comment]
well, it worked. Kinda.

```
nate@Nate-WarRig:/media/nate/Bulk SSD/bin/Rhythm-Bot$ node main.js
Disconnected.
Error: Incorrect login details were provided.
    at WebSocketManager.client.ws.once.event (/media/nate/Bulk SSD/bin/Rhythm-Bot/node_modules/discord.js/src/client/ClientManager.js:36:41)
    at WebSocketManager.g (events.js:292:16)
    at emitOne (events.js:96:13)
    at WebSocketManager.emit (events.js:188:7)
    at WebSocketManager.eventClose (/media/nate/Bulk SSD/bin/Rhythm-Bot/node_modules/discord.js/src/client/websocket/WebSocketManager.js:195:10)
    at WebSocket.ws.onclose (/media/nate/Bulk SSD/bin/Rhythm-Bot/node_modules/discord.js/src/client/websocket/WebSocketManager.js:82:35)
    at WebSocket.onClose (/media/nate/Bulk SSD/bin/Rhythm-Bot/node_modules/ws/lib/WebSocket.js:446:14)
    at emitTwo (events.js:106:13)
    at WebSocket.emit (events.js:191:7)
    at WebSocket.cleanupWebsocketResources (/media/nate/Bulk SSD/bin/Rhythm-Bot/node_modules/ws/lib/WebSocket.js:950:8)
```

**Comment by nate2014jatc** [comment]
Scratch the last comment, I was being an idiot and I pasted a web address into the token field.

Perhaps I should get some sleep XP

**Comment by Malexion** [comment]
Hmm still seems to be related to the login process, hard to say what it is.

Oh I had to google to figure out what you meant by "THE Rhythm Bot" wow I never knew that existed, I just made this clunky thing about a year ago since I couldn't find any operational music bots at the time.

But it looks like https://rythmbot.co/ is just my bot on steroids with sharding to allow easy creation, you could probably rework mine to be just like that if you wanted though it'd take some time.
