### ISSUE TITLE
Volume adjustment leads to error

### ISSUE THREAD

**Issue by nate2014jatc** [Malexion/Rhythm-Bot#10]
I have no idea what's going on here XD
I just barely spun him up, and he's making strange things happen.
![image](https://user-images.githubusercontent.com/11836893/51787701-5171ba80-2132-11e9-90bb-5875bbaccb1c.png)

**Comment by Malexion** [comment]
Ha yeah I probably should have done more clarity on this, I probably have some lingering errors to fix but the volume is limited to 50% - 200% by discord.js

If I have some time to rewrite it ill try to figure something out

**Comment by Malexion** [comment]
To add onto that when you set volume itll take a % chunk out of that 150% gap and add it to 50, so setting it to 0 will set it to 50%

Theres probably a better way to do this now, not sure

**Comment by nate2014jatc** [comment]
thank you for the response!

I think I remember your bot having support for playlists in the past, is that correct?

**Comment by Malexion** [comment]
Yeah you can use the playlist command to create a playlist out of whatever is in your current queue

**Comment by nate2014jatc** [comment]
Sorry for not being clear, I meant the ability to load YouTube playlists from their url.
