### ISSUE TITLE
Boot fail

### ISSUE THREAD

**Issue by zuto-kun** [Malexion/Rhythm-Bot#11]
It says the bot isn't fully booted even when it is and it stops us from using some commands
Example
https://drive.google.com/file/d/1wFCUKCTrmuWzFPGCBUIViobTaltEjiVe/view?usp=drivesdk

**Comment by nate2014jatc** [comment]
Are you self-hosting the files from this repo, or using [this guy](https://rythmbot.co/)?

**Comment by zuto-kun** [comment]
Wait
This isn't the actual repository for it?
Sorry to waste your time then

**Comment by nate2014jatc** [comment]
I was confused by that too!
This is a good bot though, if you don't mind running your own code.

11/10 would `git clone` again

On February 6, 2019 8:42:09 AM UTC, zuto-kun <notifications@github.com> wrote:
>Wait
>This isn't the actual repository for it?
>Sorry to waste your time then
>
>-- 
>You are receiving this because you commented.
>Reply to this email directly or view it on GitHub:
>https://github.com/Malexion/Rhythm-Bot/issues/11#issuecomment-460942535

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by Malexion** [comment]
Yeah my bad on the naming convention I think my bot repo and that service went up at about the same time.

Looking to rewrite the bot at some point in typescript hopefully so its easier to follow along and wont be as jumbled.
