### ISSUE TITLE
unable to play anything

### ISSUE THREAD

**Issue by BRAVO68WEB** [Malexion/Rhythm-Bot#15]
music bot unable to join any voice channel
it says song added
but nothing happens when using !play

**Comment by BRAVO68WEB** [comment]
I added the song using both !youtube and !add url command the songs are add to to queue also but the bot didn't joined the voice channel !join and !play is not working plzzz help

**Comment by Malexion** [comment]
Will take a look, might be a ytdl update.

**Comment by Malexion** [comment]
@BRAVO68WEB I'm not encountering any errors, do you have anything from the console log or the bot.log file?

**Comment by BRAVO68WEB** [comment]
How to get log files

**Comment by BRAVO68WEB** [comment]
Sry for late reply

**Comment by Malexion** [comment]
Should be at the same level as your bot-config.json

![image](https://user-images.githubusercontent.com/5237473/62577681-11b82800-b865-11e9-9602-45f5223f1842.png)
