### ISSUE TITLE
When adding it asks for type

### ISSUE THREAD

**Issue by DziugisLT** [Malexion/Rhythm-Bot#16]
When I add a song to queue it asks for type... I tried everything from youtube to all wikipedia media types and so on. It doesn't add songs

**Comment by Malexion** [comment]
Ah the format might be confusing I probably need to change it.

`!add youtube:https://www.youtube.com/watch?v=oHg5SJYRHA0`

`!add youtube:oHg5SJYRHA0`

You can also do:

`!youtube oHg5SJYRHA0`
