### ISSUE TITLE
bot is not joining channel!

### ISSUE THREAD

**Issue by nxtlo** [Malexion/Rhythm-Bot#17]
(node:14736) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 14)

(node:13820) UnhandledPromiseRejectionWarning: Error: FFMPEG not found
(node:13820) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
(node:13820) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by Malexion** [comment]
Your missing the FFMPEG install outlined in the README.md file

https://www.ffmpeg.org/

Have to make sure you add the install path to your system path.
