### ISSUE TITLE
Error adding track: Unknown Media Type!

### ISSUE THREAD

**Issue by o0oMrMercyo0o** [Malexion/Rhythm-Bot#20]
Hi, i cant seem to see why the bot wont add any music.  it will either say 
Error adding track: Unknown Media Type! or
Error adding track: Error: This video is unavailable

The commands i have tried using is !add, !add youtube (url), !youtube. 

please advise me. thanks

**Comment by Malexion** [comment]
What's the full command you have tried with a url/part?

**Comment by o0oMrMercyo0o** [comment]
please join my discord so i can show you. ive managed to get it working up to the point of the bot joining. it adds music to the queue. but does not play when you !play. even when something is in the queue. and its saying its found 19 vulnerabilities. 

https://discord.gg/eWswun4

**Comment by mattzaharias** [comment]
I've run into this exact issue after finally getting the bot up and running and added to my discord server.  It joins the voice channel but then says:

Strife.Modus Today at 8:49 AM: !add https://music.youtube.com/watch?v=sn7LRxjgN7k&feature=share
Malexion-Rhythm-Bot2 BOT Today at 8:49 AM:
Error
Error adding track: Unknown Media Type!

I've tried adding an individual song as well as a playlist that I listen to constantly.

**Comment by Malexion** [comment]
Updated ytdl-core in latest release which most likely should fix it.

@mattzaharias I don't currently have it setup to pull in playlists rather the playlist command will save/load the current queue locally

**Comment by Malexion** [comment]
For playlists I'll probably try to integrate something like this in the future https://www.npmjs.com/package/ytpl
