### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by Marsietis** [Malexion/Rhythm-Bot#3]
Can you help  me? 
![error 2](https://user-images.githubusercontent.com/25828370/34079666-a3719ed6-e33a-11e7-9050-57330b733529.PNG)

**Comment by Marsietis** [comment]
And i have Plugins

**Comment by Malexion** [comment]
Looks like the folder is missing from src/plugins. I think it missed the git check in.

**Comment by Malexion** [comment]
Folder should exist now if you pull again.
