### ISSUE TITLE
Command collisions

### ISSUE THREAD

**Issue by 5cript** [Malexion/Rhythm-Bot#7]
The bot commands such as clear collide with other bots that provide this command. 
I therefore propose a prefix to every command, or at least a prefix mode for backwards compatibility that can be enabled.

**Comment by Malexion** [comment]
If you look in main.js you can change the command prefix to anything you want, just by editing the string to the right of symbol.

```
const bot = new RhythmBot({
    command: {
        symbol: '-' // command symbol trigger
    },
    ...
});
```
