### ISSUE TITLE
Crash on -play

### ISSUE THREAD

**Issue by Darkness1337** [Malexion/Rhythm-Bot#8]
Me: starts the bot
Me: -enqueue youtube:https://www.youtube.com/watch?v=dQw4w9WgXcQ
bot::heavy_plus_sign: Enqueued: "undefined" @ #1
Me: -join
*bot joins*
me: -play
*bot crash*

**Comment by iTrustmaster** [comment]
Same

**Comment by Malexion** [comment]
ytdlcore probably updated and broke it all, I'll update when I get a chance.

**Comment by DreBigs** [comment]
I'm having this issue as well. I am unable to fix it as it would seem.

**Comment by Malexion** [comment]
Finally had some time, ydtl-core and node opus were out of date, latest fixes this. 

You may have to update those dependencies and rebuild node-opus with gyp or you can grab latest and carry over anything you need.

Hoping to rebuild the project at some point here in typescript probably with more clarity.
