### ISSUE TITLE
Rythm responding to bots

### ISSUE THREAD

**Issue by diegoheg** [Malexion/Rhythm-Bot#9]
How can i make rythm respond to bots in the chat? Is there any command or something that i can do in my bot to make rythm respond to it?

**Comment by Malexion** [comment]
Limitation of discord js, bot chat has a seperate event from player chat I think? So theoretically could be done

**Comment by JasonTheMain** [comment]
By default its off because selfbotting is against the rules so its on a fine line

**Comment by viluzi** [comment]
i want this
i need this
please
